#!/bin/sh

MODULE_DIR="/lib/modules/$(uname -r)/extra"
MODE="664"

load_faulty()
{
    module="faulty"
    device="faulty"

    echo "Loading ${module}"
    insmod "$MODULE_DIR/${module}.ko" || exit 1

    major=$(awk "\$2==\"$module\" {print \$1}" /proc/devices)

    if [ -n "$major" ]; then
        rm -f /dev/${device}
        mknod /dev/${device} c $major 0
        chmod $MODE /dev/${device}
    else
        echo "No device found in /proc/devices for driver ${module}"
    fi
}

unload_faulty()
{
    echo "Unloading faulty"
    rmmod faulty || exit 1
    rm -f /dev/faulty
}

load_scull()
{
    module="scull"
    device="scull"

    echo "Loading ${module}"
    insmod "$MODULE_DIR/${module}.ko" || exit 1

    major=$(awk "\$2==\"$module\" {print \$1}" /proc/devices)

    if [ -z "$major" ]; then
        echo "No major number found for scull"
        exit 1
    fi

    rm -f /dev/${device}[0-3]
    mknod /dev/${device}0 c $major 0
    mknod /dev/${device}1 c $major 1
    mknod /dev/${device}2 c $major 2
    mknod /dev/${device}3 c $major 3
    ln -sf ${device}0 /dev/${device}
    chmod $MODE /dev/${device}[0-3]

    rm -f /dev/${device}pipe[0-3]
    mknod /dev/${device}pipe0 c $major 4
    mknod /dev/${device}pipe1 c $major 5
    mknod /dev/${device}pipe2 c $major 6
    mknod /dev/${device}pipe3 c $major 7
    ln -sf ${device}pipe0 /dev/${device}pipe
    chmod $MODE /dev/${device}pipe[0-3]

    rm -f /dev/${device}single
    mknod /dev/${device}single c $major 8
    chmod $MODE /dev/${device}single

    rm -f /dev/${device}uid
    mknod /dev/${device}uid c $major 9
    chmod $MODE /dev/${device}uid

    rm -f /dev/${device}wuid
    mknod /dev/${device}wuid c $major 10
    chmod $MODE /dev/${device}wuid

    rm -f /dev/${device}priv
    mknod /dev/${device}priv c $major 11
    chmod $MODE /dev/${device}priv
}

unload_scull()
{
    echo "Unloading scull"
    rmmod scull || exit 1

    rm -f /dev/scull /dev/scull[0-3]
    rm -f /dev/scullpriv
    rm -f /dev/scullpipe /dev/scullpipe[0-3]
    rm -f /dev/scullsingle
    rm -f /dev/sculluid
    rm -f /dev/scullwuid
}

case "$1" in
    start)
        echo "Starting ldd modules"

        modprobe hello || exit 1
        load_faulty
        load_scull
        ;;

    stop)
        echo "Stopping ldd modules"

        unload_scull
        unload_faulty
        rmmod hello || exit 1
        ;;

    restart)
        "$0" stop
        "$0" start
        ;;

    *)
        echo "Usage: $0 {start|stop|restart}"
        exit 1
        ;;
esac

exit 0